version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # TODO: add your code here (delete this line and follow the indent conventions)
  app:
    build: ./backend
    environment:
      - REDIS_HOST=redis
    ports:
      - "9900:9900"
    depends_on:
      - redis
  frontend:
    build: ./frontend
    depends_on:
      - app
    ports:
      - "3901:3000"
